-- Add new bonus questions

INSERT INTO public.bonus_questions (question_text, option_a, option_b, option_c, option_d, correct_answer, reward_amount) VALUES
('Which country won the 2022 FIFA World Cup?', 'Brazil', 'Argentina', 'France', 'Germany', 'B', 10000000),
('Who is known as ''CR7''?', 'Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Kylian Mbappe', 'B', 10000000),
('How many players are on the field per team in a standard soccer match?', '9', '10', '11', '12', 'C', 10000000),
('Which position is primarily responsible for stopping goals?', 'Forward', 'Goalkeeper', 'Midfielder', 'Defender', 'B', 10000000),
('What is it called when a player scores three goals in one match?', 'Hat-trick', 'Brace', 'Double', 'Quadruple', 'A', 10000000),
('Which country has appeared in the most FIFA World Cup finals without winning?', 'Netherlands', 'Hungary', 'Poland', 'Sweden', 'A', 10000000),
('Who was the youngest player to score in a FIFA World Cup match?', 'Pelé', 'Kylian Mbappe', 'Michael Owen', 'Wayne Rooney', 'D', 10000000),
('Which player scored the fastest goal in World Cup history?', 'Hakan Şükür', 'David Villa', 'Claudio Pizarro', 'Luis Hernandez', 'A', 10000000),
('Which country won the first ever UEFA European Championship in 1960?', 'Soviet Union', 'Yugoslavia', 'Spain', 'Italy', 'B', 10000000),
('Which team has the record for most consecutive Premier League wins?', 'Manchester City', 'Arsenal', 'Liverpool', 'Chelsea', 'D', 10000000),
('Which club won the treble (League, Cup, Champions League) in 1999?', 'Barcelona', 'Manchester United', 'Inter Milan', 'AC Milan', 'B', 15000000),
('Which formation is commonly used in “tiki-taka” possession style?', '4-4-2', '4-3-3', '3-5-2', '4-2-3-1', 'B', 15000000),
('Who holds the record for most goals in a single UEFA Champions League season?', 'Robert Lewandowski', 'Lionel Messi', 'Cristiano Ronaldo', 'Karim Benzema', 'C', 15000000),
('Which country hosted the first FIFA Women’s World Cup?', 'USA', 'China', 'Norway', 'Germany', 'B', 15000000),
('Which player has the record for most assists in a single World Cup tournament?', 'Thomas Muller', 'Lionel Messi', 'Cristiano Ronaldo', 'Kaka', 'A', 15000000),
('Which country has won the most Copa America titles?', 'Uruguay', 'Argentina', 'Brazil', 'Chile', 'C', 15000000),
('Which club has won the most consecutive La Liga titles?', 'Real Madrid', 'Barcelona', 'Atletico Madrid', 'Valencia', 'B', 15000000),
('Which player scored the winning goal in the 2014 World Cup final?', 'Mario Gotze', 'Thomas Muller', 'Neymar', 'James Rodriguez', 'A', 15000000),
('Which country has won the most FIFA Confederations Cups?', 'Brazil', 'France', 'Spain', 'Argentina', 'D', 15000000),
('Which team is known as “The Invincibles” for a season without losses?', 'Arsenal', 'Manchester United', 'Juventus', 'AC Milan', 'A', 15000000),
('Who scored the “Goal of the Century” in 1986 World Cup?', 'Pelé', 'Diego Maradona', 'Michel Platini', 'Zico', 'B', 20000000),
('Which club has won the most UEFA Europa League titles?', 'Sevilla', 'Juventus', 'Inter Milan', 'Valencia', 'A', 20000000),
('Which player has played in the most FIFA World Cups?', 'Lothar Matthäus', 'Antonio Carbajal', 'Roger Milla', 'Gianluigi Buffon', 'B', 20000000),
('Which national team was nicknamed “The Golden Team” in the 1950s?', 'Hungary', 'Spain', 'Germany', 'Italy', 'A', 20000000),
('Which player has scored the most goals in UEFA European Championship history?', 'Michel Platini', 'Cristiano Ronaldo', 'Wayne Rooney', 'Thierry Henry', 'B', 20000000),
('Which manager has won the most UEFA Champions League titles?', 'Alex Ferguson', 'Carlo Ancelotti', 'Jose Mourinho', 'Zinedine Zidane', 'D', 20000000),
('Which country has won both the men’s and women’s FIFA World Cup?', 'Germany', 'USA', 'Brazil', 'France', 'B', 20000000),
('Who is the all-time top scorer for the French national team?', 'Antoine Griezmann', 'Kylian Mbappe', 'Thierry Henry', 'Michel Platini', 'C', 20000000),
('Which club has the record for most consecutive Bundesliga titles?', 'Bayern Munich', 'Borussia Dortmund', 'Schalke 04', 'Leipzig', 'A', 20000000),
('Which player has the fastest red card in Premier League history?', 'David Beckham', 'Keith Gillespie', 'Wayne Rooney', 'Patrick Vieira', 'B', 20000000),
('Which country hosted the 1998 FIFA World Cup?', 'France', 'South Korea', 'USA', 'Brazil', 'A', 20000000),
('Which player scored the most goals in a single Premier League season?', 'Alan Shearer', 'Mohamed Salah', 'Erling Haaland', 'Thierry Henry', 'C', 20000000);
