// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igqoymrqtxabszyzqavl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncW95bXJxdHhhYnN6eXpxYXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDg0NzUsImV4cCI6MjA3Mzk4NDQ3NX0.pzgJbPLIhHp7dElMtFH3_mQAUAQsWajXrZ_UcjImE3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});